### ISSUE TITLE
Context expression being parenthesized

### ISSUE THREAD

**Issue by leana8959** [Enter-tainer/typstyle#129]
Hello,

I noticed that (after commit `2cab26dc9d6dcd31115c65a3eec43689020ae654`), functions where the entire body is in a context keyword is parenthesized. Was this intended ?
This doesn't affect let bindings that are not functions.

I thought that, compared to how if statements are not enclosed in parentheses, this is a bit inconsistent.

Example:

<summary>Before</summary>

```typ
#let foo() = context {
  5
}
```

<summary>After</summary>

```typ
#let foo() = (
  context {
    5
  }
)
```

<summary>`if` expressions are not in parentheses</summary>

```typ
#let foo() = if true {
  5
} else {
  6
}
```

Thanks a lot and have a nice day :)

**Comment by Enter-tainer** [comment]
This is related to #114 regards to parenthesizes around expressions. Ideally, we should maintain the length of the first line of the expression, if the length of `#let foo() = context {` exceed the column width, we should switch to
```
#let foo() = (
  context {
    ...  
}
)
```

However this is hard to implement in currect pretty printer. I cannot remember why I decide to do this. Maybe this is because changing this can make my testset looks better.
