### ISSUE TITLE
escape hatch not respected inside `if` statement

### ISSUE THREAD

**Issue by ntjess** [Enter-tainer/typstyle#182]
Cross-posting as requested from https://github.com/Myriad-Dreamin/tinymist/issues/996

According to the [docs](https://github.com/Enter-tainer/typstyle?tab=readme-ov-file#escape-hatch):
> If you find typstyle is not working as expected, you can use // @typstyle off or /* @typstyle off */ to disable the formatter on the next node of code.

However, neither comment style prevents tinymist from applying formatting in certain circumstances.

```typst
#if true {
  // @typstyle off
  let x = (
  "A message that will be split into multiple lines to ensure that each"
  + " line does not exceed sixty characters in length. This is a common"
  + " practice to improve readability and maintainability of the code."
  )
  // @typstyle on
}
```
Without the if block, the escape hatch works. Inside if, it fails.

_Side note: I think splitting operators to their own lines is a "favorable" default behavior compared to merging them into one line when the result would be very long_

**Comment by QuadnucYard** [comment]
In the lastest release version of typst (not updated in tinymist yet), your code is formatted as:
```typ
#if true {
  // @typstyle off
  let x = (
    "A message that will be split into multiple lines to ensure that each"
      + " line does not exceed sixty characters in length. This is a common"
      + " practice to improve readability and maintainability of the code."
  )
  // @typstyle on
}
```
(Binary chain is here!)

After looking into the case, I found some defects.

Firstly, in your example, the directive `// @typstyle off` actually applies to the `Code` in the code block that wraps `let`. However, we do not check whether formatting `Code` is disabled, since we mix it into the code block in our process.
It seems that it is not the `if` expression but the code block that caused this bug.

Secondly, in the code below, the directive takes effect on `#` instead of the let-binding.

```typ
// @typstyle off
#let x = ()
```

Besides, `@typstyle on` is not a valid directive. We simply check whether the comment contains `@typstyle off` to decide whether to format the next expression.

Thanks for your bug report! 😄

**Comment by ntjess** [comment]
I see, thanks for the detailed response!
